server:
  port: 8443

spring:
  datasource:
    username: root
    password: dengjiaming123
    url: jdbc:mysql://3.248.182.99:3306/cinema?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 3.248.182.99 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
#    username: defalut # Redis服务器连接用户名（默认为空）
    password: dengjiaming123 # Redis服务器连接密码（默认为空）
    timeout: 1000ms # 连接超时时间
    lettuce:
      pool:
        max-active: 100 # 连接池最大连接数
        max-idle: 100 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制

mybatis:
  type-aliases-package: com.fivesix.fivesixserver.entity
  mapper-locations: classpath:/mapper/*.xml

